CREATE TABLE `BET_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `SPORT` varchar(125) DEFAULT NULL,
  `RESULTS` varchar(26000) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `STAGE` varchar(60) DEFAULT NULL,
  `BET_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) 