CREATE TABLE BET_HISTORY
(
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255),
  SPORT VARCHAR(125),
  RESULTS VARCHAR(36000),
  DATE DATE,
  STAGE VARCHAR(60),
  BET_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LINK VARCHAR(200),
  NOTES VARCHAR(400),
  COMPETITION VARCHAR(300)
);
CREATE INDEX BET_HISTORY__title ON BET_HISTORY (TITLE);


CREATE TABLE CURRENT_BET_STATUS
(
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  WIN_LAST_BET INT(11) DEFAULT '0',
  CURRENT_AMOUNT DOUBLE DEFAULT '0',
  LAST_LOSE_BETS_SUM DOUBLE DEFAULT '0'
);